{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "try:  code \n",
    "\n",
    "except Exception as e: (multiple except are allowed) if prob in try block code, exception will run\n",
    "\n",
    "else: (Optional) if no error in try code block, else block one will exceute \n",
    "\n",
    "finally:(Optional)  will excecute in all situation\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "a= 10 \n",
    "a/0\n",
    "print(\"use this code \")\n",
    "\n",
    "a = 10 \n",
    "b = int(input( ))\n",
    "a/b\n",
    "\n",
    "try:\n",
    "    a = 10\n",
    "    b = int(input())\n",
    "    c = a/b\n",
    "    print(c)\n",
    "except Exception as e :\n",
    "    print(\"there was an issue with b var \") \n",
    "    print(e)\n",
    "    \n",
    "    \n",
    "\n",
    "try :\n",
    "    a = input()\n",
    "    b = int(a)\n",
    "    print(b)\n",
    "except Exception as e :\n",
    "    print(\"code will come to this block once there will be an issue with try \")\n",
    "    print(e)\n",
    "else :\n",
    "    print(\"this will be executed once try will be able to finish itself otherwise it will not execute this \")\n",
    "\n",
    "try :\n",
    "    a = int(input())\n",
    "    b = int(input())\n",
    "    c = a + b \n",
    "except Exception as e :\n",
    "    print(\"this is inside Exception block\" ) \n",
    "    print(e) \n",
    "except IOError as e :\n",
    "    print(\" in case of failure it will come to this block \")\n",
    "    print(e)\n",
    "    print(\"this is inside IOerror block \") \n",
    "except ArithmeticError as e :\n",
    "    print(e)\n",
    "    print(\"this is inside arithmetic error block \")\n",
    "except FileNotFoundError as e :\n",
    "    print(e)\n",
    "    print(\"this is inside Filenotfound error block \") \n",
    "except ValueError as e :\n",
    "    print(e) \n",
    "    print(\"this is inside value error block \") \n",
    "\n",
    "else :\n",
    "    print(\"this will be executed once try will be able to finish itself otherwise it will not execute this \")\n",
    "finally:\n",
    "    print(\"it will execute itself in all the situation\")\n",
    "    \n",
    "\n",
    "def test1():\n",
    "    try :\n",
    "        \n",
    "        a = int(input(\"enter an integer \"))\n",
    "        return a \n",
    "    except :\n",
    "        print(\"ask to a user to enter a value again \")\n",
    "        try :\n",
    "            \n",
    "            a = int(input(\"enter an integer\"))\n",
    "        except:\n",
    "            print(\"this is second time user has made a mistake \")\n",
    "    else :\n",
    "        print(\"fsdfdfssfdsf\")\n",
    "    finally:\n",
    "        print(\"finally i will execute \")\n",
    "\n",
    "\n",
    "test1()\n",
    "\n",
    "def test2():\n",
    "    while True :\n",
    "        try :\n",
    "            a = int(input(\"enter an integer\"))\n",
    "            try :\n",
    "                print(\"this is a try inside try \")\n",
    "                b = input()\n",
    "            except:\n",
    "                print(\"this is a part of nesterd try \")\n",
    "        except Exception as e :\n",
    "            print(\"this is an issue \", e )\n",
    "            continue\n",
    "        else : \n",
    "            print(\"it a able to execute try with success\")\n",
    "            print(a)\n",
    "            break        \n",
    "\n",
    "test2()\n",
    "\n",
    "a = 10 \n",
    "b = 5 \n",
    "c = a /b \n",
    "\n",
    "c\n",
    "\n",
    "10/5\n",
    "\n",
    "def cust_exception(a) :\n",
    "    if a < 5: \n",
    "        raise Exception(a)\n",
    "        \n",
    "\n",
    "cust_exception(3)\n",
    "\n",
    "try :\n",
    "    a = int(input())\n",
    "    cust_exception(a)\n",
    "except Exception as e :\n",
    "    print(e)\n",
    "\n",
    "def cust_exception(a):\n",
    "    if a < 5:\n",
    "        raise Exception(\"Less than 5\")\n",
    "    else:\n",
    "        return a\n",
    "\n",
    "cust_exception(3)\n",
    "\n",
    "l = [\"sudh\" , 5 ,6 ]\n",
    "for i in l :\n",
    "    try :\n",
    "        div  = int(i) / int(i)\n",
    "        print(div)\n",
    "    except Exception as e :\n",
    "        print(e)\n",
    "\n",
    "try :\n",
    "    a = int(input(\"enter an interger\"))\n",
    "    print(\"this is a entered value\" ,a )\n",
    "    if a < 0 :\n",
    "        raise ValueError(\"this is not a positive interger you have entered\" , a)\n",
    "except ValueError as e :\n",
    "    print(\"Fsdfs\",e)\n",
    "\n",
    "import math \n",
    "def test3(a):\n",
    "    if type(a) != int:\n",
    "        raise TypeError(\"this is a typing mistake\" , a)\n",
    "    elif a < 0 :\n",
    "        raise Exception(\"value is negative \",a)\n",
    "    else :\n",
    "        print(math.sqrt(a))\n",
    "\n",
    "try:\n",
    "    test3(\"45554\")\n",
    "except Exception as e :\n",
    "    print(e)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
